[project]
name = "veloci-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abudora-0", email = "m.abdullah21306@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "selectolax>=0.4.10",
    "yt-dlp>=2026.7.4",
]

[project.scripts]
veloci-engine = "veloci_engine:main"

[build-system]
requires = ["uv_build>=0.11.23,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.21.0",
]
